# Generated by Django 6.1 on 2026-10-01 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('update_requests', '0004_remove_solicitacao_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Arquivo do documento anexado', upload_to='documentos_solicitacoes/')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='update_requests.solicitacao')),
            ],
        ),
    ]
