# Generated by Django 6.1 on 2026-10-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SUPPORTING', 'Documento Comprobatório'), ('REVIEW', 'Parecer / Justificativa')], default='SUPPORTING', max_length=20, verbose_name='Categoria do Documento')),
                ('document_type', models.CharField(choices=[('SALARY', 'Comprovante de Renda'), ('ADDRESS', 'Comprovante de Endereço'), ('PROPERTY', 'Documento de Imóvel'), ('VEHICLE', 'Documento de Veículo'), ('JUSTIFICATION', 'Justificativa de Ajuste/Reprovação'), ('APPROVAL_NOTE', 'Termo de Efetivação')], max_length=30, verbose_name='Tipo de Documento')),
                ('display_name', models.CharField(help_text='Nome do arquivo para exibição na interface', max_length=255, verbose_name='Nome de Exibição')),
                ('file', models.FileField(help_text='Arquivo do documento anexado', upload_to='request_documents/', verbose_name='Arquivo')),
                ('related_item_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='Índice do Item Relacionado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Documento da Solicitação',
                'verbose_name_plural': 'Documentos da Solicitação',
            },
        ),
    ]
