# Generated by Django 6.1 on 2026-10-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('update_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocument',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='update_requests.request', verbose_name='Solicitação'),
        ),
    ]
