# Generated by Django 6.1 on 2026-10-10 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_requestdocument_and_more'),
        ('update_requests', '0007_request_vehiclesnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocument',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='update_requests.request', verbose_name='Solicitação'),
        ),
        migrations.DeleteModel(
            name='DocumentosSolicitacao',
        ),
    ]
