# Generated by Django 6.1 on 2026-08-31 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_remove_cliente_residencia_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAntigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco_snapshot', models.CharField(max_length=400)),
                ('cep_snapshot', models.CharField(max_length=8)),
                ('tem_imoveis_snapshot', models.BooleanField(default=False)),
                ('tem_veiculos_snapshot', models.BooleanField(default=False)),
                ('qtd_imoveis_snapshot', models.IntegerField(default=0)),
                ('qtd_veiculos_snapshot', models.IntegerField(default=0)),
                ('dados_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DadosNovos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('residencia_endereco', models.CharField(max_length=400)),
                ('residencia_cep', models.CharField(max_length=8)),
                ('imovel_endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('imovel_bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('imovel_cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('imovel_cep', models.CharField(blank=True, max_length=8, null=True)),
                ('veiculo_renavam', models.CharField(blank=True, max_length=11, null=True)),
                ('veiculo_placa', models.CharField(blank=True, max_length=7, null=True)),
                ('veiculo_marca_modelo', models.CharField(blank=True, max_length=90, null=True)),
                ('veiculo_ano', models.CharField(blank=True, max_length=9, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('dados_antigos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis_snapshot', to='update_requests.dadosantigos')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enavam', models.CharField(blank=True, max_length=11, null=True)),
                ('placa', models.CharField(blank=True, max_length=7, null=True)),
                ('marca_modelo', models.CharField(blank=True, max_length=90, null=True)),
                ('ano', models.CharField(blank=True, max_length=9, null=True)),
                ('dados_antigos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_snapshot', to='update_requests.dadosantigos')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_gn', models.IntegerField()),
                ('atualizacao', models.CharField(choices=[('Renda', 'Atualização de Renda'), ('Patrimônio', 'Atualização de Patrimônio'), ('Endereço', 'Atualização de Endereço')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado'), ('PENDING_AGENCY_REVIEW', 'Pendente Análise'), ('APPROVED', 'Aprovado'), ('NEEDS_ADJUSTMENT', 'Necessita Ajuste'), ('PENDING_CADASTRO', 'Pendente Cadastro'), ('UPDATED', 'Atualizado'), ('COMPLETED', 'Concluído'), ('REJECTED', 'Rejeitado')], default='DRAFT', max_length=30)),
                ('documento', models.URLField(help_text='URL do documento anexado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='customers.cliente')),
                ('dados_antigos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_com_dados_antigos', to='update_requests.dadosantigos')),
                ('dados_novos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_com_dados', to='update_requests.dadosnovos')),
            ],
        ),
        migrations.AddField(
            model_name='dadosnovos',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_solicitacoes_novos', to='update_requests.solicitacao'),
        ),
        migrations.AddField(
            model_name='dadosantigos',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_solicitacao_antigos', to='update_requests.solicitacao'),
        ),
    ]
