# Generated by Django 6.1 on 2026-09-23 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshotveiculo',
            old_name='enavam',
            new_name='renavam',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='dados_antigos',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='dados_novos',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='id_gn',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou a solicitação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='documento',
            field=models.FileField(help_text='Arquivo do documento anexado', upload_to='documentos_solicitacoes/'),
        ),
    ]
