# Generated by Django 6.1 on 2026-10-10 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('update_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou a solicitação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='proposeddata',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_data', to='update_requests.request', verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='previousdata',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_data', to='update_requests.request', verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='vehiclesnapshot',
            name='previous_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_snapshots', to='update_requests.previousdata', verbose_name='Dados Anteriores'),
        ),
    ]
