# Generated by Django 6.1 on 2026-09-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_requests', '0002_rename_enavam_snapshotveiculo_renavam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDING_AGENCY_REVIEW', 'Pendente Análise do GA'), ('PENDING_CADASTRO', 'Pendente Análise do Time de Cadastro'), ('NEEDS_ADJUSTMENT_GN', 'Necessita Ajuste do GN'), ('NEEDS_ADJUSTMENT_GA', 'Necessita Ajuste do GA'), ('UPDATED', 'Atualizado'), ('REJECTED', 'Rejeitado')], default='PENDING_AGENCY_REVIEW', max_length=30),
        ),
    ]
