# Generated by Django 6.1 on 2026-10-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_requests', '0003_alter_solicitacao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='documento',
        ),
    ]
