# Generated by Django 6.1 on 2026-10-03 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_requests', '0004_remove_solicitacao_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosnovos',
            name='imovel_bairro',
        ),
        migrations.RemoveField(
            model_name='dadosnovos',
            name='imovel_cep',
        ),
        migrations.RemoveField(
            model_name='dadosnovos',
            name='imovel_cidade',
        ),
        migrations.RemoveField(
            model_name='dadosnovos',
            name='imovel_endereco',
        ),
        migrations.RemoveField(
            model_name='dadosnovos',
            name='veiculo_ano',
        ),
        migrations.RemoveField(
            model_name='dadosnovos',
            name='veiculo_marca_modelo',
        ),
        migrations.RemoveField(
            model_name='dadosnovos',
            name='veiculo_placa',
        ),
        migrations.RemoveField(
            model_name='dadosnovos',
            name='veiculo_renavam',
        ),
        migrations.AlterField(
            model_name='dadosantigos',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_antigos', to='update_requests.solicitacao'),
        ),
        migrations.AlterField(
            model_name='dadosnovos',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_novos', to='update_requests.solicitacao'),
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('dados_novos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to='update_requests.dadosnovos')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renavam', models.CharField(blank=True, max_length=11, null=True)),
                ('placa', models.CharField(blank=True, max_length=7, null=True)),
                ('marca_modelo', models.CharField(blank=True, max_length=90, null=True)),
                ('ano', models.CharField(blank=True, max_length=9, null=True)),
                ('dados_novos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='update_requests.dadosnovos')),
            ],
        ),
    ]
