# Generated by Django 6.1 on 2026-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_requests', '0005_remove_dadosnovos_imovel_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosnovos',
            name='residencia_cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='dadosnovos',
            name='residencia_endereco',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='dadosnovos',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='atualizacao',
            field=models.CharField(choices=[('Renda', 'Atualização de Renda'), ('Imóvel', 'Atualização de Patrimônio Relacionado a Imóveis'), ('Veículo', 'Atualização de Patrimônio Relacionado a Veículos'), ('Endereço', 'Atualização de Endereço')], max_length=20),
        ),
    ]
