# Generated by Django 6.1 on 2026-10-10 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_remove_veiculo_cliente_property_vehicle_and_more'),
        ('update_requests', '0006_alter_dadosnovos_residencia_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_salary_update', models.BooleanField(default=False, verbose_name='Atualiza Renda?')),
                ('has_address_update', models.BooleanField(default=False, verbose_name='Atualiza Endereço?')),
                ('has_property_update', models.BooleanField(default=False, verbose_name='Atualiza Imóveis?')),
                ('has_vehicle_update', models.BooleanField(default=False, verbose_name='Atualiza Veículos?')),
                ('status', models.CharField(choices=[('PENDING_AGENCY_REVIEW', 'Pendente Análise do GA'), ('PENDING_REGISTRATION', 'Pendente Análise do Time de Cadastro'), ('NEEDS_ADJUSTMENT_GN', 'Necessita Ajuste do GN'), ('NEEDS_ADJUSTMENT_GA', 'Necessita Ajuste do GA'), ('UPDATED', 'Atualizado'), ('REJECTED', 'Rejeitado')], default='PENDING_AGENCY_REVIEW', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.CreateModel(
            name='VehicleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renavam', models.CharField(blank=True, max_length=11, null=True, verbose_name='RENAVAM')),
                ('plate', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa')),
                ('brand_model', models.CharField(blank=True, max_length=90, null=True, verbose_name='Marca/Modelo')),
                ('year', models.CharField(blank=True, max_length=9, null=True, verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Snapshot de Veículo',
                'verbose_name_plural': 'Snapshots de Veículos',
            },
        ),
        migrations.RemoveField(
            model_name='dadosantigos',
            name='dados_referencia',
        ),
        migrations.RemoveField(
            model_name='dadosantigos',
            name='solicitacao',
        ),
        migrations.RemoveField(
            model_name='snapshotveiculo',
            name='dados_antigos',
        ),
        migrations.RemoveField(
            model_name='snapshotimovel',
            name='dados_antigos',
        ),
        migrations.RemoveField(
            model_name='dadosnovos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='dadosnovos',
            name='solicitacao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='dados_novos',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='dados_novos',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='criado_por',
        ),
        migrations.CreateModel(
            name='PreviousData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_snapshot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Snapshot de Salário')),
                ('address_snapshot', models.CharField(max_length=400, verbose_name='Snapshot de Endereço')),
                ('cep_snapshot', models.CharField(max_length=8, verbose_name='Snapshot de CEP')),
                ('has_properties_snapshot', models.BooleanField(default=False, verbose_name='Possui Imóveis (Snapshot)')),
                ('has_vehicles_snapshot', models.BooleanField(default=False, verbose_name='Possui Veículos (Snapshot)')),
                ('properties_count_snapshot', models.IntegerField(default=0, verbose_name='Qtd. Imóveis (Snapshot)')),
                ('vehicles_count_snapshot', models.IntegerField(default=0, verbose_name='Qtd. Veículos (Snapshot)')),
                ('reference_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Cliente de Referência')),
            ],
            options={
                'verbose_name': 'Dados Anteriores (Snapshot)',
                'verbose_name_plural': 'Dados Anteriores (Snapshots)',
            },
        ),
        migrations.CreateModel(
            name='PropertySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=150, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('previous_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_snapshots', to='update_requests.previousdata', verbose_name='Dados Anteriores')),
            ],
            options={
                'verbose_name': 'Snapshot de Imóvel',
                'verbose_name_plural': 'Snapshots de Imóveis',
            },
        ),
        migrations.CreateModel(
            name='ProposedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Proposto')),
                ('residence_address', models.CharField(blank=True, max_length=400, null=True, verbose_name='Endereço Residencial Proposto')),
                ('residence_cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP Residencial Proposto')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dados Propostos',
                'verbose_name_plural': 'Dados Propostos',
            },
        ),
        migrations.CreateModel(
            name='ProposedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço')),
                ('neighborhood', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('proposed_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='update_requests.proposeddata', verbose_name='Dados Propostos')),
            ],
            options={
                'verbose_name': 'Imóvel Proposto',
                'verbose_name_plural': 'Imóveis Propostos',
            },
        ),
        migrations.CreateModel(
            name='ProposedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renavam', models.CharField(blank=True, max_length=11, null=True, verbose_name='RENAVAM')),
                ('plate', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa')),
                ('brand_model', models.CharField(blank=True, max_length=90, null=True, verbose_name='Marca/Modelo')),
                ('year', models.CharField(blank=True, max_length=9, null=True, verbose_name='Ano')),
                ('proposed_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='update_requests.proposeddata', verbose_name='Dados Propostos')),
            ],
            options={
                'verbose_name': 'Veículo Proposto',
                'verbose_name_plural': 'Veículos Propostos',
            },
        ),
    ]
