# Generated by Django 6.1 on 2026-08-31 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('update_requests', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_novo', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado'), ('PENDING_AGENCY_REVIEW', 'Pendente Análise'), ('APPROVED', 'Aprovado'), ('NEEDS_ADJUSTMENT', 'Necessita Ajuste'), ('PENDING_CADASTRO', 'Pendente Cadastro'), ('UPDATED', 'Atualizado'), ('COMPLETED', 'Concluído'), ('REJECTED', 'Rejeitado')], max_length=21)),
                ('status_antigo', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado'), ('PENDING_AGENCY_REVIEW', 'Pendente Análise'), ('APPROVED', 'Aprovado'), ('NEEDS_ADJUSTMENT', 'Necessita Ajuste'), ('PENDING_CADASTRO', 'Pendente Cadastro'), ('UPDATED', 'Atualizado'), ('COMPLETED', 'Concluído'), ('REJECTED', 'Rejeitado')], max_length=21)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('solicitacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='update_requests.solicitacao')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='users.usuarios')),
            ],
        ),
    ]
