# Generated by Django 6.1 on 2026-10-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('IP_ADDRESS', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('APPROVE', 'Aprovação'), ('REJECT', 'Reprovação'), ('REQUEST_ADJUSTMENT', 'Solicitação de Ajuste'), ('EDIT', 'Solicitação Ajustada'), ('EFFECT', 'Efetivação'), ('STATUS_CHANGE', 'Mudança de Status')], default='STATUS_CHANGE', max_length=20, verbose_name='Ação Executada')),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Anterior')),
                ('new_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Novo Status')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Justificativa / Parecer')),
                ('changes_payload', models.JSONField(blank=True, null=True, verbose_name='Payload de Alterações')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
            },
        ),
    ]
