# Generated by Django 6.1 on 2026-10-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('update_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='update_requests.request', verbose_name='Solicitação'),
        ),
    ]
