# Generated by Django 6.1 on 2026-10-10 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_remove_logs_solicitacao_remove_logs_usuario'),
        ('update_requests', '0007_request_vehiclesnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='update_requests.request', verbose_name='Solicitação'),
        ),
    ]
