# Generated by Django 6.1 on 2026-08-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='residencia',
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
