# Generated by Django 6.1 on 2026-09-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_cliente_residencia_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
