# Generated by Django 6.1 on 2026-10-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_remove_veiculo_cliente_property_vehicle_and_more'),
        ('update_requests', '0007_request_vehiclesnapshot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
